title: "Redundancy and Bloat seen in AAA Game Engines"
description: "Overengineering in AAA Game Engines"
baseurl: "/Redundancy-seen-in-AAA-game-engines"
url: "https://zero-irp.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

author: z1rp
email: Zer0_1rp@proton.me
show_excerpts: true

minima:
  skin: dark
